### ISSUE TITLE
VS2017 error on build solution: bootstrapper.lib can't find

### ISSUE THREAD

**Issue by nazimnc** [wolfreak99/audio-router#15]
when i build solution in VS 2017 , find following error

Severity	Code	Description	Project	File	Line	Suppression State
Error	

LNK1104	cannot open file 'C:\audio-router-develop\audio-router-develop\bin\Debug\Win32\bootstrapper\bootstrapper.lib'	 LINK	1

**Comment by wolfreak99** [comment]
https://www.google.com/search?q=LNK1104
